- name: install unzip
  apt:
    name: unzip
    state: latest
    force: yes

- name: download wordpress
  get_url:
    url: "http://wordpress.org/wordpress-{{ wp_version }}.zip"
    dest: "/usr/local/src/wordpress-{{ wp_version }}.zip"

- name: ensure wordpress target directory exists
  file: path="{{ wp_nginx_root }}" state=directory mode=0755
  
- name: unzip wordpress
  unarchive:
    src: "/usr/local/src/wordpress-{{ wp_version }}-ja.zip"
    dest: "{{ wp_nginx_root }}"
    creates: "{{ wp_nginx_root }}/wordpress"
    owner: "{{ wp_owner }}"
    group: "{{ wp_group }}"
    copy: no

- name: modify wp-config.php
  template:
    src: wp-config.php
    dest: "{{ wp_nginx_root }}/wordpress/wp-config.php"
    owner: "{{ wp_owner }}"
    group: "{{ wp_group }}"
    mode: 0644

- include: nginx.yml
- include: mysql.yml
